### ISSUE TITLE
Basic Code format

### ISSUE THREAD

**Issue by seito2** [HottoCoffee/pre-HottoCoffee#14]
- [x] yamlのquote (single or double)
- [x] Github Actionsのvaluesをquoteで囲うか否か

**Comment by seito2** [comment]
@tikogr @T45K 上記２つ、どっちが良いですかね
自分は
- single quote
- 必要がないときは囲わない（できるだけシンプルに）

派です

**Comment by T45K** [comment]
それで良いかなと思います

**Comment by T45K** [comment]
あと配列どう書くか

**Comment by seito2** [comment]
```
property1: [hoge, foo] 
```
or 

```
property1
  - hoge
  - foo
```
?

**Comment by T45K** [comment]
はい

**Comment by seito2** [comment]
配列は統一しない（好み）

**Comment by T45K** [comment]
配列で`[a, b]`みたいな書き方をすると`[`とか`,`の前後のスペースどうするみたいな話に発展しそうだなと思いました
